# lexicons.py

# 1) PROFANITY (แบ่งเบา/หนัก)
PROFANITY_MILD = {
    "ass", "asses", "crap", "crappy", "damn", "damned", "damning", "fuck", "fucked",
    "hell", "hells", "bloody", "bloodyhell", "bugger", "bollocks",
    "idiot", "jerk", "jerks", "lameass", "manwhore", "mong", "numbnuts",
    "tosser", "wanker", "wankers", "wankerish"
}

PROFANITY_STRONG = {
    "asshole", "assholes", "bastard", "bastards", "bitch", "bitches",
    "bollocksed", "bullcrapping", "bullshit", "bullshits", "cock", "cocks",
    "cocksucker", "cocksuckers", "dick", "dicks", "dickhead", "dickheads",
    "dildo", "dyke", "dykes", "fag", "faggot", "faggots",
    "fucker", "fuckers", "fucking", "fucks", "goddamn", "jackass", "jackasses",
    "jizz", "knob", "knobs", "motherfucker", "motherfuckers", "piss", "pissed",
    "pissing", "prick", "pricks", "pussy", "pussies", "shit", "shits", "shitted",
    "shitting", "slut", "sluts", "twat", "twats", "whore", "whores", "arse",
    "arsehole", "bitchy", "bollocksed", "cockhead", "cockwomble", "cum",
    "cumming", "cunt", "cunted", "cunting", "dammit", "dickish", "dickwad",
    "effing", "feck", "fecker", "fuckface", "fuckhead", "fucknut", "fuckwit",
    "frigger", "fubar", "holyshit", "horseshit", "jerkwad", "minger", "muff",
    "punani", "shitbag", "shitface", "shitfaced", "slutbag", "smegma",
    "twatwaffle", "arsewipe", "assclown", "asshat", "asslick", "assmonkey",
    "assmunch", "bellend", "berk", "cack", "cackhead", "cockbite", "cockbrain",
    "cocklick", "cockroach", "cumdump", "cumface", "cumfuck", "cummer",
    "cunthole", "cunty", "dingleberry", "dipshit", "doochbag", "dork", "dorkface",
    "douche", "douchebag", "douchecanoe", "douchewaffle", "dumbass", "dumbfuck",
    "fagbag", "fagface", "fagfuck", "fatass", "fucka", "fuckboy", "fuckfreak",
    "fuckhole", "fuckoff", "fuckshit", "fucktard", "fuckup", "fudgepacker",
    "fuuck", "fuk", "fuker", "gash", "git", "gobshite", "gobshites", "gobshyte",
    "gobsmacked", "holyfuck", "idiotic", "jackhole", "knobhead", "muffdiver",
    "numpty", "prat", "pratface", "pube", "puss", "pussylicker", "pussywhipped",
    "shite", "shited", "shitehead", "shites", "shiting", "shitty", "slag", "slapper",
    "slutface", "slutty", "sonofabitch", "spastic", "twunt", "wankbag", "wankjob",
    "arsehole", "asslicker", "assmonkey", "assnugget", "asswipe", "bastardly",
    "bollocking", "buggerall", "bullcrapper", "bullshithead", "bummer",
    "cockalicious", "cockfaced", "cockhead", "cockknocker", "cocklicker",
    "cockmonster", "cocksplat", "cocksucking", "crapola", "crapper", "crapstick",
    "cuntlick", "cuntlicker", "cuntwaffle", "dickbag", "dicklicker", "dickweed",
    "dickwad", "dildoed", "dingle", "dorkface", "douchebagged", "douchecanoe",
    "douchewaffle", "dumbfuckery", "dykeface", "faggo", "faghead", "fagot",
    "fannyflaps", "fannyfucker", "feckface", "flamer", "fuckfaced", "fucknutty",
    "fuckshitface", "fuckwad", "fuckwit", "fuq", "gashface", "gitface",
    "gobsmacked", "holyfucker", "horseshite", "jackassery", "jerkwad", "kuntface",
    "lameasshole", "manwhore", "minge", "mongoloid", "muffdiver", "numbnuts",
    "pissface", "prickface", "pubehead", "punani", "pussface", "shitbagger",
    "shitfaced", "shitfuck", "shithead", "shitstain", "skank", "slutbag",
    "slutface", "sonofabitch", "spastic", "tosser", "twatwaffle", "twunt",
    "wankbag", "wanker", "wankerish", "wankjob", "whoreface"
}


# 2) SEXUAL (explicit)
SEXUAL_MILD = {
    "sex", "s3x", "pussy", "pussies", "puzzy", "pussi", "vajayjay",
    "vag", "vage", "vagene", "vagin", "tits", "boobs", "hooters",
    "jugs", "melons", "bazongas", "knockers", "rack", "titties", "titty",
    "nipple", "nipples", "areola", "booty", "bootylicious", "thicc",
    "panties off", "moaning", "moan", "horny", "aroused", "turned on","naked", "nude"
}

SEXUAL_STRONG = {
    "fucked", "fucks", "motherfucker", "mf", "mofo", "nudity",
    "cocksucker", "cock sucking", "suck cock", "blowjob", "blow job", "bj",
    "handjob", "hand job", "rimjob", "rim job", "gangbang", "gang bang", "gang-bang",
    "threesome", "foursome", "orgy", "orgasm", "deepthroat", "deep throat",
    "jerk off", "jack off", "wank", "wanking", "get laid", "bang", "banging",
    "shag", "hump", "humping", "dry hump", "fingerbang", "finger bang", "titfuck",
    "tittyfuck", "tit-job", "titjob", "titty job", "creampie", "cumshot", "cum shot",
    "money shot", "facefuck", "face fuck", "facesitting", "face sitting", "doggy style",
    "doggystyle", "anal", "anal sex", "buttsex", "assfuck", "ass fuck", "assfucking",
    "ass licking", "asslicking", "eat ass", "eat booty", "69", "sixty-nine", "strip",
    "stripping", "stripper", "lapdance", "lap dance", "come", "cum", "cumming", "jizz",
    "bust a nut", "nutting", "nut", "spunk", "milf", "gilf", "dilf", "cougar", "hookup",
    "hook up", "booty call", "fap", "fapping", "masturbate", "masturbation", "self suck",
    "selfsuck", "fellate", "fellatio", "suck off", "screwing", "rawdog", "raw dogging",
    "raw-dog", "bareback", "breeding", "sexed", "sext", "sexting", "throatfuck",
    "throat fuck", "spitroast", "spit roast", "dick", "dicks", "dickhead", "dick head",
    "dickhole", "dickbag", "dickwad", "dickweed", "dickless", "cock", "cocks", "c0ck",
    "kok", "kock", "penis", "shaft", "member", "dong", "schlong", "pecker", "phallus",
    "nuts", "ball sack", "ballsack", "sack", "scrotum", "testicles", "nards",
    "nads", "wiener", "weiner", "weenie", "knob", "tool", "package", "junk", "one-eyed monster",
    "meatstick", "piss stick", "rocket", "rod", "manhood", "man meat", "hard-on", "hardon",
    "boner", "wood", "woodie", "willy", "johnson", "jawn", "cunt", "cunts", "twat", "twats",
    "clit", "clitty", "clitoris", "muff", "coochie", "coochy", "cooter", "punani", "poon", "p00n",
    "poontang", "beaver", "fur burger", "fish taco", "cameltoe", "camel toe", "cum", "cums",
    "cumming", "jizzed", "jiz", "sperm", "semen", "load", "big load", "cream", "cream pie",
    "dripping", "wetness", "lubed", "lube", "gusher", "sticky", "melting", "porn", "porno",
    "pornographic", "p0rn", "pr0n", "nsfw", "camgirl", "camboy", "cam model", "camwhore",
    "live sex", "xxx", "hardcore", "softcore", "fetish", "erotic", "erotica", "hentai",
    "rule34", "rule 34", "slut", "sluts", "slutty", "slutbag", "slutface", "whore", "wh0re",
    "hoe", "ho", "skank", "tramp", "thot", "thottie", "thotty", "easy girl", "cum dumpster",
    "cumdump", "cumslut", "fucktoy", "fleshlight", "bimbo", "nympho", "nymphomaniac",
    "gold digger", "pussy whipped", "manwhore", "homewrecker", "fck", "fk", "f", "f@ck",
    "f4ck", "f-ck", "f_ck", "f u c k", "f.u.c.k", "fu_ck", "fuxk", "fvck", "fvk", "cck",
    "c**k", "c0ck", "c0cks", "c0x", "d1ck", "d!ck", "d!k", "pssy", "p**sy", "p@ssy",
    "puy", "pu5sy", "p.u.s.s.y", "p u s s y", "wh0re", "wh*re", "w.h.o.r.e", "sl*t", "sl@t",
    "c*nt", "c**t", "c#nt", "tw*t", "t.w.a.t", "j!zz", "j1zz", "j!z", "b00bs", "b00b",
    "t!ts", "t1ts", "t!tty", "t!tties", "a$$hole", "@ss", "@sshole", "a55",
    "nutbuster", "nutjob", "backshots", "back shot", "hit it", "tap that", "tap it",
    "pound", "getting pounded", "spread", "open wide", "wide open", "ride him", "ride me",
    "she riding", "rail her", "rail me", "pipe", "giving pipe", "lay pipe", "plow", "plowed",
    "bent over", "from behind", "doggy", "reverse cowgirl", "cowgirl", "missionary",
    "quickie", "nooner", "after sex", "sexcapade", "smash", "smashed", "smashing",
    "hit her raw", "slippery", "bdsm", "bondage", "dom", "domme", "dominatrix", "sub",
    "submissive", "master", "mistress", "pegging", "peg", "spanking", "choking", "breathplay",
    "roleplay", "role play", "leather play", "kink", "kinky", "fetish", "foot fetish",
    "feet fetish", "boot fetish", "latex fetish", "bondage play", "rope play", "shibari",
    "nipple play", "wax play", "impact play", "sensory play","breast"
}

# 3) VIOLENCE (เนื้อหารุนแรง)
VIOLENT_MILD = {
    "abuse", "abused", "abusive", "harass", "harassed", "harassing", "threat",
    "threaten", "threatened", "threatening", "intimidate", "intimidated", "intimidating",
    "menace", "menaced", "menacing", "rough", "rough up", "roughing up",
    "fight", "fighting", "brawl", "brawling", "wrestle", "wrestled", "wrestling",
    "push down the stairs", "push him down the stairs", "push her down the stairs"
}

VIOLENT_STRONG = {
    "ambush", "ambushed", "ambushing", "annihilate", "annihilated", "annihilating", "annihilation",
    "assassinate", "assassinated", "assassinating", "assassination", "assassin", 
    "assault", "assaulted", "assaulting", "attack", "attacked", "attacking",
    "batter", "battered", "battering", "batterer", "beat", "beaten", "beating",
    "beat up", "beat down", "beat to death", "beat senseless", "beat unconscious",
    "brutal", "brutality", "brutalize", "brutalized", "brutalizing",
    "burn", "burned", "burning", "burn alive", "burned alive",
    "bomb", "bombed", "bombing", "bombard", "bombarded", "bombarding",
    "bloodbath", "bloodshed", "blow up", "blown up", "blow his head off", "blow her head off",
    "body slam", "body-slam", "body-slammed", "body-slamming",
    "break", "break bones", "break his arm", "break her arm", "break his neck", "break her neck",
    "broken bones", "broken skull", "broken jaw",
    "bullet", "bullets", "bullet wound", "butcher", "butchered", "butchering",
    "carnage", "carnal violence", "choke", "choked", "choking", "choke out", "choke him", "choke her", "choke to death",
    "chop", "chopped", "chopping", "chop off",
    "cleave", "cleaved", "cleaving",
    "club", "clubbed", "clubbing",
    "clobber", "clobbered", "clobbering",
    "collide", "collision", "combat", "combatant", "combatants",
    "crash", "crashed", "crashing",
    "crush", "crushed", "crushing", "crush his skull", "crush her skull", "crush bones",
    "cut", "cut up", "cut open", "cut throat", "cut his throat", "cut her throat", "cutting",
    "deadly", "deadly attack", "deadly blow", "deadly force", "deadly hit", "deadly strike",
    "decapitate", "decapitated", "decapitating", "decapitation",
    "deface", "defaced", "defacing",
    "defile", "defiled", "defiling",
    "demolish", "demolished", "demolishing",
    "destroy", "destroyed", "destroying", "destruction",
    "devastate", "devastated", "devastating", "devastation",
    "dismember", "dismembered", "dismembering", "dismemberment",
    "domestic violence", "domestic abuse",
    "drive-by", "drive-by shooting", "eliminate", "eliminated", "eliminating",
    "execution", "execute", "executed", "executing",
    "explode", "exploded", "exploding", "explosion", "explosive", "explosives",
    "extort", "extorted", "extorting", "extortion",
    "eye gouge", "gouge", "gouged", "gouging",
    "force", "forced", "forceful", "forcefully",
    "fracture", "fractured", "fracturing", "fractured skull", "fractured ribs",
    "gang fight", "gang violence", "gang war", "gang warfare",
    "genocide", "gruesome", "gruesome attack", "gruesome murder", "gruesome killing",
    "gore", "gory", "gory details", "gory scene",
    "gun", "guns", "gunshot", "gunshots", "gunfire", "gunfight", "gunfight scene", "gunpoint",
    "hack", "hacked", "hacking", "hack apart",
    "hang", "hanged", "hanging",
    "harm", "harmed", "harming",
    "headbutt", "head-butt", "headbutted", "headbutting",
    "headshot", "head-shotted", "head-shoot",
    "home invasion",
    "hunt", "hunted", "hunting", "hunt down",
    "injure", "injured", "injuring", "injury",
    "kick", "kicked", "kicking", "kick hard", "kick in the face", "kick in the head", "kick to the ribs",
    "knee to the face", "knee strike",
    "knife", "knifed", "knifing", "knife fight",
    "lacerate", "lacerated", "lacerating", "laceration",
    "lynch", "lynched", "lynching", "kill", "killed", "killing", "killer", "kill zone",
    "maim", "maimed", "maiming",
    "manhandle", "manhandled", "manhandling",
    "massacre", "massacred", "massacring", "mass killing", "mass murder",
    "military attack", "military strike",
    "murder", "murdered", "murdering", "murderous", "murderous rage",
    "neutralize", "neutralized", "neutralizing",
    "oppress", "oppressed", "oppressing", "oppression",
    "pistol whip", "pistol-whip", "pistol-whipped", "pistol-whipping",
    "rape threat",
    "rob", "robbed", "robbing", "robbery",
    "shoot", "shoot at", "shoot down", "shoot up", "shooting", "shot", "shot him", "shot her", "shot dead", "shot to death",
    "stab", "stabbed", "stabbing", "stab to death", "stab multiple times", "stab wound", "stab wounds",
    "strangle", "strangled", "strangling", "strangle to death",
    "terror", "terrorize", "terrorized", "terrorizing",
    "torture", "tortured", "torturing", "torturous",
    "wound", "wounded", "wounding",
    "whip", "whipped", "whipping",
    "wreck", "wrecked", "wrecking", "wreck his face", "wreck her face", "wreck the place",
    "armed", "armed attack", "armed robbery", "armed assault", "armored strike",
    "axe attack", "axe", "axe swing",
    "backhand", "backhanded", "backhand punch",
    "backstab", "backstabbed", "backstabbing",
    "bash", "bashed", "bashing", "bash his head", "bash her head",
    "battery the door", "battering ram",
    "beat bloody", "beat raw", "beat senseless", "beat to a pulp", "beat to a bloody pulp",
    "black eye", "blood on the floor", "blood on his hands", "blood on her hands",
    "blood on their hands", "bloody nose",
    "bone-crushing", "bone shattering",
    "close-range shot", "club to death",
    "combat knife", "corpse", "corpses",
    "cripple", "crippled", "crippling blow",
    "crossfire", "crossfire casualties",
    "cruel blow", "cruel beating", "cruel treatment",
    "crush with a rock",
    "cut deep", "cut him badly", "cut her badly", "cut across his face", "cut across her face",
    "dead on the floor", "dead on arrival", "dead in the street",
    "death blow", "death punch", "death kick", "death squad",
    "defensive wound",
    "disarm", "disarmed", "disarming",
    "disfigure", "disfigured", "disfiguring",
    "do damage", "do serious harm",
    "double tap", "draw blood",
    "drive a knife", "drive a sword",
    "elbow strike", "elbow to the face",
    "execute him", "execute her", "explode a bomb", "explode a grenade",
    "eye socket fracture", "face smashed", "face smashed in", "fall under fire",
    "fatal attack", "fatal beating", "fatal blow", "fatal hit", "fatal injury", "fatal wound",
    "fire a gun", "fire shots", "fire into the crowd", "firebomb", "firebombed",
    "fist to his face", "fist to her face",
    "fracture his arm", "fracture her arm", "fracture his leg", "fracture her leg",
    "grenade", "grenade blast", "grenade explosion",
    "ground and pound",
    "gun barrel", "gun butt", "gun down", "gunman", "gunmen",
    "hammer his head", "hammer her head",
    "hand-to-hand combat",
    "hit and run", "hit squad", "hit with a bat", "hit with a brick", "hit with a chair",
    "hold at gunpoint", "hurl a brick", "hurl a rock", "inflict damage",
    "inflict deep wounds", "inflict severe pain", "injure badly", "intense beating",
    "iron bar attack", "kick his ribs", "kick her ribs", "kick his head", "kick her head",
    "kick him while he’s down", "kick her while she’s down",
    "knee his face", "knee her face", "knife to the throat", "knife to his throat",
    "knife to her throat", "knock his teeth out", "knock her teeth out",
    "land a blow", "land a hard punch", "leave him bleeding", "leave her bleeding",
    "leave him for dead", "leave her for dead",
    "leg sweep", "life-threatening injury", "lift and slam", "lock in a choke", "lock in a hold",
    "loop of barbed wire", "lose blood", "mass beating", "mass brawl", "massive head trauma",
    "massive bleeding", "mauled", "mauling", "military violence", "neck snap",
    "negligent discharge", "no holds barred fight", "open fire", "open up on them",
    "pelt with rocks", "pelt with bottles", "pepper with bullets", "permanent scar",
    "pierce", "pierced", "piercing wound", "pistol shot", "pistol round", "plunge a knife",
    "plunge a blade", "pound on his chest", "pound on her chest", "pummel", "pummeled",
    "pummeling", "ram into", "rammed into", "ranged attack", "repeated blows", "repeated punching",
    "rip skin", "rip flesh", "rip him apart", "rip her apart", "riot police clash",
    "rip through flesh", "rip through his body", "rip through her body",
    "shoot on sight", "shoot to kill", "shoulder check", "shove into a wall", "shove to the ground",
    "skull fracture", "slam", "slammed", "slamming", "slam his head", "slam her head",
    "slash across his face", "slash across her face", "snap his arm", "snap her arm",
    "sniper", "sniper fire", "sniper shot", "spatter blood", "spilled blood", "spray bullets",
    "stab him in the back", "stab her in the back", "stab in the chest", "stab in the gut",
    "stab repeatedly", "steel pipe attack", "storm the building", "strike his face", "strike her face",
    "strike with force", "sucker punch", "sudden attack", "sustained beating",
    "target with violence", "tear skin", "tear his skin", "tear her skin",
    "threat with a knife", "threat with a gun", "throw a punch", "throw a rock",
    "throw a brick", "throw a chair", "throw him down", "throw her down",
    "thrown into a wall", "thrown across the room", "thump", "thumped", "thumping",
    "torment", "tormented", "tormenting", "total destruction", "tug of war",
    "turn violent", "vicious knife attack", "vicious punch", "vicious kick",
    "violent clash", "violent confrontation", "violent explosion", "violent hit",
    "violent mob", "violent protest", "violent retaliation", "violent struggle",
    "violent suppression", "violent takeover", "violent temper", "violent uprising",
    "violent war", "war", "warfare", "war crime", "war crimes",
    "whirlwind of punches", "whip lash", "wield a knife", "wield a gun", "wield a weapon",
    "wipe the floor with him", "wipe the floor with her", "wound deep", "wounded soldier",
    "wrestling slam", "wrestling throw", "wrench his arm", "wrench her arm", "wrestle to the ground"
}

# 4) HATE
HATE_SLURS = {
    "abbie", "abeed", "aboe", "apeshit", "apeshite",
    "bean queen", "beaner", "beaners", "blacky", "buttermilk",
    "cholo", "coolie", "coon", "coonies", "coons",
    "dago", "darkass", "darky", "dothead", "injun",
    "jap", "jewboy", "kike", "kneegrows", "mong",
    "mongrel", "negro", "redskin", "rice monkey", "sambo",
    "spic", "spics", "wet back", "wop", "wophead",
    "c00n", "c00nies", "camel jockey", "ch1nk", "chingchong", "chink", "chinky",
    "darkfuck", "darkshit", "darktard", "dune coon", "gook", "greaser", "groid",
    "higg3r", "higg@", "higga", "higger", "higgers", "holy fuck",
    "jigaboo", "jigaboos", "jigga", "jiggaboo", "jiggabooboo", "jiggaboos", "jiggabu",
    "jiggas", "jigger", "jiggerboo", "jiggerboos", "jiggs", "jiggyboo", "jigro",
    "k!k3", "k!ke", "k..!ke", "k1k3", "n1ckker", "n1g3r", "n1g3rz", "n1gg3r", "n1gg3rs",
    "n1gg@", "n1gg@hs", "n1gga", "n1ggah", "n1ggahs", "n1ggas", "n1ggazes", "n1gger", "n1ggers",
    "n1gguh", "n3gro", "negga", "neggar", "negr0", "negroes", "negroid",
    "nicka", "nickas", "nicker", "nickk3r", "nickker", "nig", "nig-nog", "niga", "nigah",
    "nigasses", "nigers", "nigg4h", "nigg4hs", "nigg@s", "nigg@z", "nigg@zzes",
    "nigga", "nigga lover", "niggah", "niggahs", "niggahz", "niggass", "niggaz", "niggazzes",
    "nigger", "nigger lover", "niggerz", "niggir", "niggress", "nigguhs", "nigguhz",
    "niglet", "nignigs", "nignog", "nigra", "nigre", "nigs", "niguh", "nikk3r", "nikkas",
    "nikker", "nuckas", "nuggets", "oven dodger", "paki", "pancake face", "porch monkey",
    "raghead", "ragheads", "ragtard", "tacohead", "tar-baby", "timber nigger",
    "towelhead", "towelheads", "towelshithead", "we1back", "wigger", "zip in the wire", "zipperhead",
    "shiester", "shiesterfuck", "shiesterfuckface", "shiesterfuckhead", "shiesterfucks", "shylock",
    "sl@nteye", "slantard", "slanteye b1tch", "slanteyes", "slanteyeshit", "slantfreak", "slanty",
    "spicfuck"
}

SEX_EDU_WHITELIST = {
    "sex education",
    "sex and gender",
    "sex in school",
    "sex chromosome",
    "sex differences",
}
